name: L1 tests

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: L1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install deps
        run: npm install
      
      - name: Start local server
        continue-on-error: false
        run: npx hardhat test
